apiVersion: apps/v1
kind: Deployment
metadata:
  name: mautic-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mautic
  template:
    metadata:
      labels:
        app: mautic
    spec:
      containers:
      - name: mautic
        image: docker.io/mautic/mautic
        ports:
        - containerPort: 80
        env:
        - name: MAUTIC_DB_HOST
          value: mysql
        - name: MAUTIC_DB_NAME
          value: mautic
        - name: MAUTIC_DB_USER
          value: mautic
        - name: MAUTIC_DB_PASSWORD
          value: password
        volumeMounts:
        - mountPath: /var/www/html/media
          name: mautic-storage
      volumes:
      - name: mautic-storage
        persistentVolumeClaim:
          claimName: mautic-pvc
