apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: n8nio/n8n
          env:
            - name: N8N_RUNNERS_ENABLED
              value: "true"
          
          ports:
            - containerPort: 5678
          volumeMounts:
            - name: n8n-persistent-storage
              mountPath: /root/.n8n
      volumes:
        - name: n8n-persistent-storage
          persistentVolumeClaim:
            claimName: n8n-pvc
