apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mautic-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  # volumeName: mautic-pv  # Nếu bạn đã có một PersistentVolume (PV) tên là mautic-pv
