apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: standard
  hostPath:
    path: /mnt/data/registry
    type: DirectoryOrCreate
