# Suggested code may be subject to a license. Learn more: ~LicenseLog:2466414973.
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  namespace: default
data:
  MYSQL_USER: "newuser"
  MYSQL_DATABASE: "newdb"
  MYSQL_ROOT_HOST: "%"