apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  labels:
    app: mysql
    component: secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}