apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
  namespace: default
data:
  MYSQL_USER: $MYSQL_USER
  MYSQL_DATABASE: $MYSQL_DATABASE
  MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
  MYSQL_PASSWORD: $MYSQL_PASSWORD