name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Kubernetes CLI
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set up Kubeconfig
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

    - name: Check secrets
      run: |
        if [ -z "$MYSQL_USER" ]; then
          echo "Error: MYSQL_USER is empty or null"
          exit 1
        fi
        if [ -z "$MYSQL_DATABASE" ]; then
          echo "Error: MYSQL_DATABASE is empty or null"
          exit 1
        fi
        if [ -z "$MYSQL_ROOT_PASSWORD" ]; then
          echo "Error: MYSQL_ROOT_PASSWORD is empty or null"
          exit 1
        fi
        if [ -z "$MYSQL_PASSWORD" ]; then
          echo "Error: MYSQL_PASSWORD is empty or null"
          exit 1
        fi

    - name: Check service logs before deploy
      run: |
        # Check logs for specific services (e.g., mysql, n8n)
        kubectl logs -n default deployment/mysql-deployment --tail=50 || echo "No logs for mysql-deployment found."
        kubectl logs -n default deployment/n8n-deployment --tail=50 || echo "No logs for n8n-deployment found."
        kubectl logs -n default deployment/registry-deployment --tail=50 || echo "No logs for registry-deployment found."

    - name: Delete Persistent Volumes (PVs) and Persistent Volume Claims (PVCs)
      run: |
        # Delete PVs and PVCs to ensure a fresh start
        kubectl delete pv --all -n default || echo "No PVs to delete."
        kubectl delete pvc --all -n default || echo "No PVCs to delete."

    - name: Apply app configmap
      run: |
        kubectl apply -f k8s_config/app-configmap.yaml -n default

    - name: Deploy application to Kubernetes
      run: |
        kubectl apply -f k8s_config/storage/ -n default
        kubectl apply -f k8s_config/services/clusterissuer/ -n default
        kubectl apply -f k8s_config/services/registry/ -n default
        kubectl apply -f k8s_config/services/n8n/ -n default
        kubectl apply -f k8s_config/services/mysql/ -n default
        kubectl apply -f k8s_config/services/phpmyadmin/ -n default
        kubectl apply -f k8s_config/ingress/ -n default
        kubectl apply -f k8s_config/metallb/l2advertisement.yaml

    - name: Restart all deployments in default namespace
      run: |
        kubectl get deployments -n default -o name | xargs kubectl rollout restart -n default
